version: '3.7'
services:
  jenkins-ansible:
    image: jimmy/jenkins-ansible
    restart: always
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8443:8080
      - 50000:50000
    volumes:
      - ./data:/var/jenkins_home
      - ./certs:/certs/client:ro
    networks:
      - jenkins

networks:
  jenkins:
