version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    env_file:
      - .env