# Read the extracted kubeconfig file
data "local_file" "kubeconfig" {
  filename = "/tmp/${var.vm_config.name}-kubeconfig.yaml"

  depends_on = [var.kubeconfig_ready]
}

# Create a helper script for easy cluster access
resource "local_file" "cluster_access_script" {
  filename = "/tmp/${var.vm_config.name}-cluster-access.sh"
  content = <<-EOT
#!/bin/bash
# K3s Cluster Access Helper Script
# Generated by Terraform for cluster: ${var.vm_config.name}

set -e

CLUSTER_NAME="${var.vm_config.name}"
VM_IP="${var.vm_ip}"
SSH_USER="${var.ssh_config.username}"
SSH_KEY="${var.ssh_config.private_key_path}"
KUBECONFIG_PATH="/tmp/$${CLUSTER_NAME}-kubeconfig.yaml"

echo "🚀 K3s Cluster Access Helper"
echo "Cluster: $CLUSTER_NAME"
echo "================================"

# Function to get VM IP if using DHCP
get_vm_ip() {
    echo "$VM_IP"
}

# Function to test SSH connectivity
test_ssh() {
    local ip=$(get_vm_ip)
    echo "🔐 Testing SSH connection to $ip..."
    if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i "$SSH_KEY" "$SSH_USER@$ip" "echo 'SSH OK'" >/dev/null 2>&1; then
        echo "✅ SSH connection successful"
        return 0
    else
        echo "❌ SSH connection failed"
        return 1
    fi
}

# Function to test kubectl access
test_kubectl() {
    echo "🎯 Testing kubectl access..."
    if [ -f "$KUBECONFIG_PATH" ]; then
        if kubectl --kubeconfig="$KUBECONFIG_PATH" get nodes >/dev/null 2>&1; then
            echo "✅ Kubectl access successful"
            kubectl --kubeconfig="$KUBECONFIG_PATH" get nodes
            return 0
        else
            echo "❌ Kubectl access failed"
            return 1
        fi
    else
        echo "❌ Kubeconfig file not found: $KUBECONFIG_PATH"
        return 1
    fi
}

# Function to show cluster info
show_cluster_info() {
    echo "📊 Cluster Information:"
    echo "   Cluster Name: $CLUSTER_NAME"
    echo "   VM IP: $(get_vm_ip)"
    echo "   SSH Command: ssh -i $SSH_KEY $SSH_USER@$(get_vm_ip)"
    echo "   Kubeconfig: $KUBECONFIG_PATH"
    echo "   Kubectl: kubectl --kubeconfig=$KUBECONFIG_PATH"
}

# Function to set up local kubeconfig
setup_kubeconfig() {
    echo "⚙️  Setting up local kubeconfig..."
    if [ -f "$KUBECONFIG_PATH" ]; then
        echo "   Kubeconfig already exists: $KUBECONFIG_PATH"
        echo "   To use this cluster, run:"
        echo "   export KUBECONFIG=$KUBECONFIG_PATH"
    else
        echo "❌ Kubeconfig not found. Run 'terraform apply' first."
        exit 1
    fi
}

# Function to show usage
show_usage() {
    echo "Usage: $0 [command]"
    echo ""
    echo "Commands:"
    echo "  info      Show cluster information"
    echo "  ssh       Test SSH connection"
    echo "  kubectl   Test kubectl access"
    echo "  setup     Set up local kubeconfig"
    echo "  connect   SSH into the cluster node"
    echo "  logs      Show K3s service logs"
    echo "  status    Show cluster status"
    echo ""
    echo "Examples:"
    echo "  $0 info"
    echo "  $0 kubectl"
    echo "  $0 connect"
}

# Function to connect via SSH
connect_ssh() {
    local ip=$(get_vm_ip)
    echo "🔗 Connecting to $CLUSTER_NAME ($ip)..."
    ssh -i "$SSH_KEY" "$SSH_USER@$ip"
}

# Function to show K3s logs
show_logs() {
    local ip=$(get_vm_ip)
    echo "📋 Showing K3s logs from $CLUSTER_NAME..."
    ssh -i "$SSH_KEY" "$SSH_USER@$ip" "sudo journalctl -u k3s -f"
}

# Function to show cluster status
show_status() {
    echo "📈 Cluster Status for $CLUSTER_NAME:"
    test_ssh && test_kubectl
    echo ""
    echo "🏷️  Cluster Details:"
    kubectl --kubeconfig="$KUBECONFIG_PATH" cluster-info 2>/dev/null || echo "❌ Could not get cluster info"
    echo ""
    echo "🖥️  Nodes:"
    kubectl --kubeconfig="$KUBECONFIG_PATH" get nodes -o wide 2>/dev/null || echo "❌ Could not get nodes"
    echo ""
    echo "🏃 System Pods:"
    kubectl --kubeconfig="$KUBECONFIG_PATH" get pods -n kube-system 2>/dev/null || echo "❌ Could not get system pods"
}

# Main script logic
case "$${1:-info}" in
    "info")
        show_cluster_info
        ;;
    "ssh")
        test_ssh
        ;;
    "kubectl")
        test_kubectl
        ;;
    "setup")
        setup_kubeconfig
        ;;
    "connect")
        connect_ssh
        ;;
    "logs")
        show_logs
        ;;
    "status")
        show_status
        ;;
    "help"|"-h"|"--help")
        show_usage
        ;;
    *)
        echo "❌ Unknown command: $1"
        show_usage
        exit 1
        ;;
esac
EOT

  file_permission = "0755"

  depends_on = [var.kubeconfig_ready]
}

# Create kubeconfig validation script
resource "local_file" "kubeconfig_validator" {
  filename = "/tmp/${var.vm_config.name}-validate-kubeconfig.sh"
  content = <<-EOT
#!/bin/bash
# Kubeconfig Validation Script
# Generated by Terraform for cluster: ${var.vm_config.name}

set -e

CLUSTER_NAME="${var.vm_config.name}"
KUBECONFIG_PATH="/tmp/$${CLUSTER_NAME}-kubeconfig.yaml"
EXPECTED_SERVER="https://${var.vm_ip}:6443"

echo "🔍 Validating kubeconfig for cluster: $CLUSTER_NAME"
echo "=================================================="

# Check if kubeconfig file exists
if [ ! -f "$KUBECONFIG_PATH" ]; then
    echo "❌ Kubeconfig file not found: $KUBECONFIG_PATH"
    echo "   Run 'terraform apply' to generate the kubeconfig"
    exit 1
fi

echo "✅ Kubeconfig file exists: $KUBECONFIG_PATH"

# Validate kubeconfig structure
echo "🔍 Validating kubeconfig structure..."

# Check for required sections
if ! grep -q "apiVersion:" "$KUBECONFIG_PATH"; then
    echo "❌ Invalid kubeconfig: missing apiVersion"
    exit 1
fi

if ! grep -q "clusters:" "$KUBECONFIG_PATH"; then
    echo "❌ Invalid kubeconfig: missing clusters section"
    exit 1
fi

if ! grep -q "users:" "$KUBECONFIG_PATH"; then
    echo "❌ Invalid kubeconfig: missing users section"
    exit 1
fi

if ! grep -q "contexts:" "$KUBECONFIG_PATH"; then
    echo "❌ Invalid kubeconfig: missing contexts section"
    exit 1
fi

echo "✅ Kubeconfig structure is valid"

# Check server URL
echo "🔍 Validating server URL..."
SERVER_URL=$(grep "server:" "$KUBECONFIG_PATH" | awk '{print $2}' | tr -d ' ')

if [ "$SERVER_URL" != "$EXPECTED_SERVER" ]; then
    echo "⚠️  Server URL mismatch:"
    echo "   Expected: $EXPECTED_SERVER"
    echo "   Found: $SERVER_URL"
else
    echo "✅ Server URL is correct: $SERVER_URL"
fi

# Test kubectl connectivity
echo "🔍 Testing kubectl connectivity..."
if command -v kubectl >/dev/null 2>&1; then
    if kubectl --kubeconfig="$KUBECONFIG_PATH" cluster-info --request-timeout=10s >/dev/null 2>&1; then
        echo "✅ Kubectl connectivity successful"

        # Get cluster info
        echo ""
        echo "📊 Cluster Information:"
        kubectl --kubeconfig="$KUBECONFIG_PATH" cluster-info

        echo ""
        echo "🖥️  Cluster Nodes:"
        kubectl --kubeconfig="$KUBECONFIG_PATH" get nodes -o wide

        echo ""
        echo "🏃 System Pods Status:"
        kubectl --kubeconfig="$KUBECONFIG_PATH" get pods -n kube-system --no-headers | wc -l | xargs echo "Total system pods:"
        kubectl --kubeconfig="$KUBECONFIG_PATH" get pods -n kube-system --field-selector=status.phase=Running --no-headers | wc -l | xargs echo "Running pods:"

    else
        echo "❌ Kubectl connectivity failed"
        echo "   Check if the cluster is running and accessible"
        exit 1
    fi
else
    echo "⚠️  kubectl not found in PATH"
    echo "   Install kubectl to test cluster connectivity"
fi

echo ""
echo "🎉 Kubeconfig validation completed successfully!"
echo ""
echo "💡 Usage examples:"
echo "   export KUBECONFIG=$KUBECONFIG_PATH"
echo "   kubectl get nodes"
echo "   kubectl get pods -A"
echo ""
echo "   Or use directly:"
echo "   kubectl --kubeconfig=$KUBECONFIG_PATH get nodes"
EOT

  file_permission = "0755"

  depends_on = [var.kubeconfig_ready]
}