---
# ansible playbook

- name: update homer static files
  hosts: all

  tasks:
  - name: Start SSH agent
    shell: eval $(ssh-agent)
    become: true

  - name: Add SSH key to agent
    shell: ssh-add ~/.ssh/github2023
    become: true

  - name: pull repository
    git:
      repo: "{{repo_url}}"
      dest: "{{homer_path}}"
      version: main
      update: yes
    become: true


