version: "2"

networks:
  gitea-network:
    driver: bridge

services:
  server:
    image: docker.gitea.com/gitea:1.24.3-rootless
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "4000:3000"
      - "2222:2222"
    networks:
      - gitea-network

  runner:
    image: gitea.jimmylab.duckdns.org/jimmy/runner:latest
    stdin_open: true      # 等同於 docker run -i
    tty: true    
    restart: always
    pull_policy: always
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "http://server:3000/"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "default"
      GITEA_RUNNER_LABELS: "n100"
    volumes:
      - ./runner/config.yaml:/config.yaml
      - ./runner/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea-network
    depends_on:
      - server
