name: Auto Tag on Merge
run-name: Create Tag for ${{ gitea.actor }}

on:
  workflow_dispatch:
  workflow_call:

jobs:
  create-tag:
    runs-on: n100
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full git history to enable tag operations

      - name: Generate and Push Tag
        run: |
          # Get the latest tag (format: v<major>.<minor>.<patch>)
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Latest Tag: $LATEST_TAG"

          # Parse version (remove 'v' prefix)
          VERSION=${LATEST_TAG#v}

          # Split into major, minor, patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"

          # Increment patch version
          PATCH=$((PATCH + 1))

          # Generate new tag
          NEW_TAG="v${MAJOR}.${MINOR}.${PATCH}"

          echo "New Tag: $NEW_TAG"

          # Configure git user (Gitea Actions Bot)
          git config user.name "Gitea Actions Bot"
          git config user.email "actions@gitea.local"

          # Create tag
          git tag $NEW_TAG

          # Push tag to remote
          git push origin $NEW_TAG
        env:
          # Gitea Actions automatically injects GITEA_TOKEN with write permissions
          # If permissions are insufficient, add an Access Token in repository settings
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 