name: Deploy homelab infrastructure
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-homelab-infra:
    runs-on: n100
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ansible run deploy k3s infra
        run: |
          ansible-playbook infra/ansible/deploy-k3s-infra.yml -vvv

      # - name: cd to infra tofu
      #   run: |
      #     cd infra/tofu/proxmox-k3s
      #     pwd
      #     ls -la

      # - name: tofu init
      #   working-directory: infra/tofu/proxmox-k3s
      #   run: |
      #     ls -la
      #     tofu init
