name: Deploy OpenWebUI and MCPO server
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀

on:
  workflow_dispatch:  # Allow manual triggering
    inputs:
      service:
        description: 'Select service to deploy'
        required: true
        default: 'both'
        type: choice
        options:
          - openwebui-stack
          - openwebui-only
          - mcpo-only


jobs:
  update-open-webui:
    runs-on: n100
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
            ${{ secrets.GITHUB_KEY}}
          
      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 192.168.68.124 >> ~/.ssh/known_hosts

      - name: Deploy OpenWebUI and MCPO server
        run: |  
          ssh jimmy@192.168.68.124 -A << 'EOF'
          # Navigate to the server path
          cd '/home/jimmy/home-server/app/openwebui'

          # Check current remote URL
          echo "Current remote URL:"
          git remote get-url origin
          
          # Use HTTPS URL for pulling (works for public repos)
          if git remote get-url origin | grep -q "git@github.com"; then
            echo "Switching to HTTPS URL for pulling..."
            git remote set-url origin https://github.com/jimmyliaoviva/home-server.git
          fi
          
          # Pull the latest changes
          git pull origin main
          
          sh start.sh --mcpo-only
          EOF

      - name: Verify deployment
        run: |
          ssh jimmy@192.168.68.124 << 'EOF'
          echo "🔍 Checking deployment status..."
          docker ps --filter "name=mcpo" --format "table {{.Names}}\t{{.Status}}\t{{.Image}}" || echo "❌ MCPO not found"

          echo "✅ Deployment verification completed!"
          EOF
