name: Deploy homelab infrastructure
run-name: ${{ gitea.actor }} is deploying K3s infrastructure with Terragrunt 🚀

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy (dev/prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      deployment_type:
        description: 'Deployment type (single-node/multi-node)'
        required: true
        default: 'single-node'
        type: choice
        options:
          - single-node
          - multi-node
      action:
        description: 'Action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  provision-runner:
    uses: ./.gitea/workflows/provision_runner.yaml
    with:
      container_name: "k3s-deploy"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GITHUB_KEY: ${{ secrets.GITHUB_KEY }}
      RUNNER_TOKEN: ${{ secrets.RUNNER_TOKEN }}
      TOKEN: ${{ secrets.TOKEN }}
  
  deploy-k3s-infra:
    needs: provision-runner
    runs-on: on-demand
    env:
      POSTGRESQL_USER: ${{ vars.POSTGRESQL_USER }}
      POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
      TF_STATE_CONN_STR: "postgres://${{ vars.POSTGRESQL_USER }}:${{ secrets.POSTGRESQL_PASSWORD }}@192.168.68.120:5432/tofu_state?sslmode=disable"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p /tmp/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/.ssh/home_server
          chmod 600 /tmp/.ssh/home_server
          echo "✅ SSH key set up at /tmp/.ssh/home_server"

      - name: Verify Terragrunt installation
        run: |
          if ! command -v terragrunt &> /dev/null; then
            echo "❌ Terragrunt is not installed"
            exit 1
          fi
          echo "✅ Terragrunt version: $(terragrunt --version)"

      - name: Verify OpenTofu installation
        run: |
          if ! command -v tofu &> /dev/null; then
            echo "❌ OpenTofu is not installed"
            exit 1
          fi
          echo "✅ OpenTofu version: $(tofu version)"

      - name: Set deployment path
        id: set_path
        run: |
          DEPLOY_PATH="infra/tofu/proxmox-k3s/environments/${{ github.event.inputs.environment }}/${{ github.event.inputs.deployment_type }}"
          echo "deploy_path=$DEPLOY_PATH" >> $GITHUB_OUTPUT
          echo "🎯 Deployment path: $DEPLOY_PATH"

      - name: Generate env-vars.hcl from secrets
        run: |
          ENV_VARS_FILE="infra/tofu/proxmox-k3s/environments/${{ github.event.inputs.environment }}/env-vars.hcl"

          echo "🔐 Generating env-vars.hcl from secrets and variables..."
          cat > "$ENV_VARS_FILE" <<'EOF'
          # Auto-generated by Gitea Actions - DO NOT COMMIT
          # Generated at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

          locals {
            # Proxmox connection configuration
            proxmox_config = {
              endpoint     = "${{ vars.N100_PROXMOX_ENDPOINT }}"
              username     = "${{ vars.N100_PROXMOX_TOKEN_ID }}"
              password     = "${{ secrets.N100_PROXMOX_TOKEN_SECRET }}"
              node         = "${{ vars.N100_PROXMOX_NODE }}"
              tls_insecure = true
              timeout      = 300
            }

            # SSH configuration
            ssh_config = {
              public_key       = "${{ secrets.SSH_PUBLIC_KEY }}"
              username         = "jimmy"
              private_key_path = "/tmp/.ssh/home_server"
            }

            # Network configuration defaults
            network_defaults = {
              gateway        = "${{ vars.NETWORK_GATEWAY }}"
              nameserver     = "8.8.8.8"
              nameserver_2   = "1.1.1.1"
              domain         = "local"
              interface_name = "eth0"
            }

            # Terraform state backend configuration
            tf_state_config = {
              user     = "${{ vars.POSTGRESQL_USER }}"
              password = "${{ secrets.POSTGRESQL_PASSWORD }}"
              host     = "192.168.68.120"
              port     = "5432"
              database = "tofu_state"
              sslmode  = "disable"
            }
          }
          EOF

          echo "✅ env-vars.hcl generated successfully"

      - name: Verify deployment path exists
        run: |
          if [ ! -d "${{ steps.set_path.outputs.deploy_path }}" ]; then
            echo "❌ Deployment path does not exist: ${{ steps.set_path.outputs.deploy_path }}"
            exit 1
          fi
          echo "✅ Deployment path exists"

      - name: Verify TF_STATE_CONN_STR
        run: |
          echo "🔍 Checking TF_STATE_CONN_STR environment variable..."
          if [ -z "$TF_STATE_CONN_STR" ]; then
            echo "❌ TF_STATE_CONN_STR is not set!"
            exit 1
          fi
          echo "✅ TF_STATE_CONN_STR is set (length: ${#TF_STATE_CONN_STR} characters)"
          # Show connection string format (mask password)
          echo "$TF_STATE_CONN_STR" | sed 's/:.*@/:***@/'

      - name: Initialize Terragrunt
        working-directory: ${{ steps.set_path.outputs.deploy_path }}
        run: |
          echo "🚀 Initializing Terragrunt for ${{ github.event.inputs.environment }} environment (${{ github.event.inputs.deployment_type }})..."
          if [ "${{ github.event.inputs.deployment_type }}" == "multi-node" ]; then
            terragrunt run-all init
          else
            terragrunt init
          fi

      - name: Validate Terragrunt configuration
        working-directory: ${{ steps.set_path.outputs.deploy_path }}
        run: |
          echo "🔍 Validating configuration..."
          if [ "${{ github.event.inputs.deployment_type }}" == "multi-node" ]; then
            terragrunt run-all validate
          else
            terragrunt validate
          fi

      - name: Plan infrastructure changes
        if: github.event.inputs.action == 'plan' || github.event.inputs.action == 'apply'
        working-directory: ${{ steps.set_path.outputs.deploy_path }}
        run: |
          echo "📋 Planning infrastructure changes..."
          if [ "${{ github.event.inputs.deployment_type }}" == "multi-node" ]; then
            echo "📊 Planning all nodes in dependency order..."
            terragrunt run-all plan
          else
            terragrunt plan
          fi

      - name: Apply infrastructure changes
        if: github.event.inputs.action == 'apply'
        working-directory: ${{ steps.set_path.outputs.deploy_path }}
        run: |
          echo "🚀 Applying infrastructure changes..."
          if [ "${{ github.event.inputs.deployment_type }}" == "multi-node" ]; then
            echo "📊 Deploying all nodes in dependency order..."
            echo "   1️⃣  Server node will be deployed first"
            echo "   2️⃣  Agent nodes will be deployed after server is ready"
            terragrunt run-all apply -auto-approve
          else
            terragrunt apply -auto-approve
          fi

      - name: Destroy infrastructure
        if: github.event.inputs.action == 'destroy'
        working-directory: ${{ steps.set_path.outputs.deploy_path }}
        run: |
          echo "⚠️  Destroying infrastructure..."
          if [ "${{ github.event.inputs.deployment_type }}" == "multi-node" ]; then
            echo "🗑️  Destroying all nodes in reverse dependency order..."
            terragrunt run-all destroy -auto-approve
          else
            terragrunt destroy -auto-approve
          fi

      - name: Show deployment status
        if: github.event.inputs.action == 'apply'
        working-directory: ${{ steps.set_path.outputs.deploy_path }}
        run: |
          echo "🎉 Deployment Summary:"
          echo "================================"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Deployment Type: ${{ github.event.inputs.deployment_type }}"
          echo "================================"

          if [ "${{ github.event.inputs.deployment_type }}" == "multi-node" ]; then
            echo ""
            echo "📊 Multi-Node Cluster Status:"
            echo "----------------------------"

            echo ""
            echo "🖥️  Server Node:"
            cd server && terragrunt output 2>/dev/null || echo "  ⚠️  No output available"
            cd ..

            echo ""
            echo "🖥️  Agent Node 1:"
            cd agent-01 && terragrunt output 2>/dev/null || echo "  ⚠️  No output available"
            cd ..

            echo ""
            echo "🖥️  Agent Node 2:"
            cd agent-02 && terragrunt output 2>/dev/null || echo "  ⚠️  No output available"
            cd ..

            echo ""
            echo "✅ To verify the cluster, SSH to the server node and run:"
            echo "   kubectl get nodes"
          else
            echo ""
            echo "📊 Single-Node Deployment:"
            terragrunt output 2>/dev/null || echo "Deployment completed"
          fi

          echo ""
          echo "================================"
          echo "🎊 Deployment completed successfully!"

      - name: Installation instructions
        if: github.event.inputs.action == 'apply'
        run: |
          echo ""
          echo "📝 Next Steps:"
          echo "================================"

          if [ "${{ github.event.inputs.deployment_type }}" == "multi-node" ]; then
            echo ""
            echo "For Multi-Node cluster, K3s needs to be installed manually:"
            echo ""
            echo "1️⃣  Install K3s on Server node:"
            echo "   SERVER_IP=\$(cd ${{ steps.set_path.outputs.deploy_path }}/server && terragrunt output -raw vm_ip 2>/dev/null)"
            echo "   ssh -i ~/.ssh/home_server jimmy@\$SERVER_IP"
            echo "   curl -sfL https://get.k3s.io | K3S_TOKEN=\"your-token\" sh -s - server --cluster-init --disable=traefik --disable=servicelb"
            echo ""
            echo "2️⃣  Install K3s on Agent nodes:"
            echo "   AGENT1_IP=\$(cd ${{ steps.set_path.outputs.deploy_path }}/agent-01 && terragrunt output -raw vm_ip 2>/dev/null)"
            echo "   ssh -i ~/.ssh/home_server jimmy@\$AGENT1_IP"
            echo "   curl -sfL https://get.k3s.io | K3S_URL=https://\$SERVER_IP:6443 K3S_TOKEN=\"your-token\" sh -"
            echo ""
            echo "   AGENT2_IP=\$(cd ${{ steps.set_path.outputs.deploy_path }}/agent-02 && terragrunt output -raw vm_ip 2>/dev/null)"
            echo "   ssh -i ~/.ssh/home_server jimmy@\$AGENT2_IP"
            echo "   curl -sfL https://get.k3s.io | K3S_URL=https://\$SERVER_IP:6443 K3S_TOKEN=\"your-token\" sh -"
            echo ""
            echo "3️⃣  Verify cluster:"
            echo "   ssh -i ~/.ssh/home_server jimmy@\$SERVER_IP"
            echo "   kubectl get nodes"
          else
            echo ""
            echo "For Single-Node deployment, K3s needs to be installed manually:"
            echo ""
            echo "1️⃣  Get the VM IP and SSH in:"
            echo "   VM_IP=\$(cd ${{ steps.set_path.outputs.deploy_path }} && terragrunt output -raw vm_ip 2>/dev/null)"
            echo "   ssh -i ~/.ssh/home_server jimmy@\$VM_IP"
            echo ""
            echo "2️⃣  Install K3s:"
            echo "   curl -sfL https://get.k3s.io | K3S_TOKEN=\"your-token\" sh -s - --disable=traefik --disable=servicelb"
            echo ""
            echo "3️⃣  Verify installation:"
            echo "   kubectl get nodes"
          fi

          echo ""
          echo "================================"

  destroy-runner:
    needs: [provision-runner, deploy-k3s-infra]
    if: always()
    uses: ./.gitea/workflows/destory_runner.yaml
    with:
      container_name: "k3s-deploy"
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      GITHUB_KEY: ${{ secrets.GITHUB_KEY }}