name: Provision gitea action Runner

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    uses: ./.gitea/workflows/build-image.yaml
    with:
      build_image: runner


  Provisioin:
    name: Start runner
    runs-on: n100
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ inputs.ssh_private_key }}
