- name: backup nextcloud
  hosts: all
  become: true  # Run commands with sudo

  tasks:
    - name: Run nextcloud.export command
      ansible.builtin.command:
        cmd: |
          sudo -u www-data nextcloud.export 

    - name: locate exported folder
      ansible.builtin.find:
        paths: "/var/snap/nextcloud/common/backups/" 
        file_type: directory
      register: folder_info

    - name: tar exported folder
      ansible.builtin.archive:
        path: "{{ folder_info.files[0].path }}"
        dest: "/home/nextcloud/nextcloud_backup.tar.gz"
        format: gz

    - name: send message to DC
      

