- name: backup nextcloud
  hosts: all
  become: true  # Run commands with sudo

  tasks:
    - name: Run nextcloud.export command
      ansible.builtin.command:
        cmd: |
          sudo -u www-data nextcloud.export 

    - name: backup nextcloud
      include_role:
        name: nextcloud
        tasks_from: backup

    - name: send message to DC
      

