- name: backup nextcloud
  hosts: all
  become: true  # Run commands with sudo
  become_method: sudo
  become_user: root

  vars:
    sudo_password: $ANSIBLE_VAULT;1.1;AES256
62386637333638323939306264666465653765356433313537613436373131613238613062343463
3666376433323534313763373636646265343266343063620a313834613935393065323231366466
32303864303761343339376336353665313432346665373266393436383735306335333163396165
3665396432646634370a393330663231623361643562613533613162363430306662346233373335
6131

  tasks:
    - name: Start
      block:
        - name: Run nextcloud.export command
          ansible.builtin.command:
            cmd: nextcloud.export 
          register: result

        - name: locate exported folder
          ansible.builtin.find:
            paths: "/var/snap/nextcloud/common/backups/" 
            file_type: directory
          register: folder_info

        - name: delete old backup
          ansible.builtin.file:
            path: "/home/nextcloud/nextcloud_backup.tar.gz"
            state: absent

        - name: tar exported folder
          ansible.builtin.archive:
            path: "{{ folder_info.files[0].path }}"
            dest: "/home/nextcloud/nextcloud_backup.tar.gz"
            format: gz

        - name: delete exported folder
          ansible.builtin.file:
            path: "{{ folder_info.files[0].path }}"
            state: absent

        - name: set status to success
          set_fact:
            status: "success"
            status_color: 255

      rescue:
        - name: set status to fail
          set_fact:
            status: "fail"
            status_color: 16711680
      always:
        - name: send message to discord webhook
          ansible.builtin.uri:
            url: "{{ discord_webhook_url }}}"
            method: POST
            body_format: json
            body:
              username: "Ansible automation bot" 
              avatar: "https://docs.ansible.com/ansible/latest/_static/images/Ansible-Mark-RGB_White.png"
              embeds: [
                        {
                          "title": 'Backup Nextcloud', 
                          "description": "Nextcloud backup operation {{status}}, \n result: {{result}}",
                          "color" : '{{ status_color }}',
                          "fields": [
                                      {
                                        "name": "status",
                                        "value": "{{status}}"
                                      },
                                      {
                                        "name": "result",
                                        "value": "{{result.stdout}}"
                                      }
                                    ]
                        }
                      ]
            status_code: 204