- name: test playbook
  hosts: all

  tasks:
  - name: hello world
    debug:
      msg: "Hello world!"

  - name: get first file name
    find:
      paths: "/var/snap/nextcloud/common/backups/"
      file_type: "file"
    register: files

  - name: print file name
    debug:
      msg: "{{ files.files }}"