- name: test playbook
  hosts: all

  tasks:
  - name: hello world
    debug:
      msg: "Hello world!"

  - name: get first file name
    ansible.builtin.find:
      paths: "/var/snap/nextcloud/common/backups/"  # Replace with the path to the folder you want to get the name of
      file_type: directory
    register: folder_info

  - name: print file name
    debug:
      msg: "{{ folder_info.files[0].path}}"

  - name: send message to discord webhook
    ansible.builtin.uri:
      url: "{{ discord_webhook_url }}"
      method: POST
      body_format: form-urlencoded
      body:
        content: "Backup Nextcloud"
        avatar_url: "https://docs.ansible.com/ansible/latest/_static/images/Ansible-Mark-RGB_White.png"
        # embeds: "[{'title': 'Backup Nextcloud', 'status': 'fail', 'color': 'red'}]"
      status_code: 204
