---
# ansible playbook

- name: update homer static files
  hosts: portainer
  vars:
    playbook_title: "Deploy homer static files"
    playbook_description: "Homer deployment"

  tasks:
  - name: Deploy homer static files
    block:
      - name: pull repository
        git:
          repo: "{{repo_url}}"
          dest: "{{homer_path}}"
          version: main
          update: yes
          key_file: ~/.ssh/github2023
        become: true

      - name: set status to success
        set_fact:
          status: "success"
          status_color: 255

    rescue:
      - name: set status to fail
        set_fact:
          status: "fail"
          status_color: 16711680
    always:
    - name: send notification
      ansible.builtin.include_role:
        name: discord-bot


