- name: test playbook
  hosts: localhost

  tasks:
  - name: hello world
    debug:
      msg: "Hello world!"

  - debug:
      msg: "{{repo_url }}"

  - debug:
      msg: "{{ discord_webhook_url }}"
