version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: always
    container_name: open-webui
    restart: always
    ports:
      - "3000:8080"
    volumes:
      - ./data:/app/backend/data

    networks:
      - openwebui-network

  mcpo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcpo
    restart: always
    volumes:
      - ./mcpo-config.json:/app/mcpo-config.json
      - mcpo-data:/tmp
    command: ["--port", "8000", "--config", "/app/mcpo-config.json"]
    networks:
      - openwebui-network

volumes:
  open-webui:
  mcpo-data:

networks:
  openwebui-network:
    driver: bridge

