# PostgreSQL Docker Compose Configuration
version: '3.8'
services:
  postgresql:
    image: postgres:18
    container_name: postgresql
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-defaultpassword}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
